[project]
name = "robot-dog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gs-usb>=0.3.0",
    "libusb>=1.0.27.post4",
    "piper-sdk>=0.6.1",
    "pymodbus>=3.8.6",
    "pyserial>=3.5",
    "python-can>=4.5.0",
]
